### ISSUE TITLE
Not available in PlayStore anymore

### ISSUE THREAD

**Issue by gggscript** [timsueberkrueb/ourgus#8]
https://play.google.com/store/apps/details?id=io.timsueberkrueb.ourgus isn't available anymore.
And https://vp.timsueberkrueb.io/dates doesn't work either.
But the app still works.

**Comment by timsueberkrueb** [comment]
Hey, aus den Play-Store-Statistiken (5 aktive Geräte) habe ich geschlossen, dass kein Bedarf mehr an der App besteht. Deswegen und da ich wenig Zeit habe, mich darum zu kümmern, habe ich beschlossen, die Serverkomponente einzustellen und die App aus dem Store zu nehmen.
Da die App eine Fallback-Url enthält, sollte sie problemlos weiterfunktionieren. Die Default-Url war ein Mirror von mir, um den Traffic auf den offiziellen Server gering zu halten und ein bisschen mehr Ausfalltoleranz zu haben.
Brauchst du Zugriff auf die Daten für ein anderes Projekt? Dann kannst Du mal @DominikStiller kontaktieren, der betreibt die offizielle Seite. Wenn du die App weiterbenutzen willst, kannst du das natürlich machen, im Notfall findest du [hier auch ein APK](https://github.com/timsueberkrueb/ourgus/releases).

**Comment by gggscript** [comment]
Hi, danke für deine schnelle Antwort.
Ich verstehe deine Erklärung, ich hatte eine eigene App erstellt, die auf https://vp.timsueberkrueb.io/dates aufgebaut hat und deswegen gefragt.
